### ISSUE TITLE
Buckets notification

### ISSUE THREAD

**Issue by someone77** [harshavardhana/minio-kafka#1]
Hi harshavardhana, 

Nice repository!

I try to figure out which bucket the notification event will be sent? 
Where the  "SQS ARNs:  arn:minio:sqs:us-east-1:1:kafka" configuration?

Thanks,Ron.

**Comment by harshavardhana** [comment]
All events will be sent.

**Comment by ronh123** [comment]
Where the "SQS ARNs: arn:minio:sqs:us-east-1:1:kafka" configuration?

**Comment by someone77** [comment]
Unfortunately, it is not working for me. 
Where the "SQS ARNs: arn:minio:sqs:us-east-1:1:kafka" configuration?

I would be happy, for your assistance.

Thanks,Ron.

**Comment by harshavardhana** [comment]
Please join https://slack.min.io

**Comment by someone77** [comment]
:|
